// Get all contacts
GET https://cse341-project1-d8p3.onrender.com/contacts
//GET https://localhost:3000/contacts

// Get contact by id
GET https://cse341-project1-d8p3.onrender.com/contacts/6aa078d0cb1560ea836079d1
//GET https://localhost:3000/contacts/6aa078d0cb1560ea836079d1